server:
    #    address: 0.0.0.0
    port: 19127
spring:
    kafka:
        bootstrap-servers: 10.36.126.103:9092,10.36.126.104:9092,10.36.126.105:9092
    application:
        name: '@project.artifactId@'
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 10
            minimum-idle: 1
            leakDetection: 15000
            idle-timeout: 25000
            max-lifetime: 600000
            auto-commit: true
        password: MbB!2023Sp
        url: jdbc:oracle:thin:@10.37.11.199:1539/ldsdb
        username: ttsp
    jpa:
        open-in-view: false
        hibernate:
          ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
                order_inserts: true
                order_updates: true
                generate_statistics: true
                jdbc:
                    batch_size: 100
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: ${ZIPKIN_SERVICE:http://10.36.126.15:9411/}
info:
    run:
        dir: ${user.dir}
        user: ${user.name}
management:
    endpoints:
        web:
            exposure:
                include: '*'
ribbon:
    ServerListRefreshInterval: 5000
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                web: DEBUG
                web.HttpLogging: INFO
                web.filter.CommonsRequestLoggingFilter: DEBUG
                orm.jpa: DEBUG
                transaction: DEBUG
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
kafka:
    bootstrap-servers: 10.36.126.103:9092,10.36.126.104:9092,10.36.126.105:9092
    #    bootstrap-servers:  10.36.126.132:9092,10.36.126.133:9092,10.36.126.134:9092
    consumer:
        timeout: 30000
        retry: 0
        groupId: mapper-group
lpb:
    cache:
        cache-names:
            EmpFccToT24:
                no-limit: false
                expire-time: 600
            EmpT24ToFcc:
                no-limit: false
                expire-time: 600
            BranchFccToT24:
                no-limit: false
                expire-time: 600
            BranchT24ToFcc:
                no-limit: false
                expire-time: 600
            AccountInfoMapping:
                no-limit: false
                expire-time: 600
security:
    basic:
        enable: false

    jwt:
        expiration: 30
        secret: JwtSecretKey
        jwtExpirationMs: 720000