server:
    #    address: 0.0.0.0
    port: 19127
spring:
    redis:
        host: ${REDIS_HOST:10.160.96.24}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:Lpb123!@#}
    kafka:
        bootstrap-servers: 10.160.96.29:9092,10.160.96.30:9092,10.160.96.31:9092,10.160.96.32:9092,10.160.96.33:9092,10.160.96.34:9092
    application:
        name: '@project.artifactId@'
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 10
            minimum-idle: 1
            leakDetection: 15000
            idle-timeout: 25000
            max-lifetime: 600000
            auto-commit: true
        password: LVp!2024!3fseiz
        url: jdbc:oracle:thin:@openapidb.lpbank.com.vn:1521/openapidb
        username: kcn_publicapi_tbs
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
                order_inserts: true
                order_updates: true
                generate_statistics: true
                jdbc:
                    batch_size: 100
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: ${ZIPKIN_SERVICE:http://10.36.126.15:9411/}
info:
    run:
        dir: ${user.dir}
        user: ${user.name}
management:
    endpoints:
        web:
            exposure:
                include: '*'
ribbon:
    ServerListRefreshInterval: 5000
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                web: DEBUG
                web.HttpLogging: INFO
                web.filter.CommonsRequestLoggingFilter: DEBUG
                orm.jpa: DEBUG
                transaction: DEBUG
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
lpb:
    cache:
        cache-names:
            JwtDTOResponse:
                useRedis: true
                expireTime: 3
security:
    basic:
        enable: false
    jwt:
        expiration: 15
        secret: JwtSecretKey
        jwtExpirationMs: 720000
